{{-- resources/views/admin/reports/show.blade.php --}}
@extends('layouts.app')
@section('title', $report->title)
@section('page-title', $report->title)
@section('page-sub', ucfirst($report->type) . ' report · ' . ucfirst($report->period))

@section('content')
<div class="d-flex gap-2 mb-4">
    <a href="{{ route('admin.reports.index') }}" class="btn-swms-secondary">
        <i class="ti ti-arrow-left"></i> Back
    </a>
    <a href="{{ route('admin.reports.csv', $report) }}" class="btn-swms-primary">
        <i class="ti ti-download"></i> Download CSV
    </a>
</div>

<div class="swms-card mb-4">
    <div class="row g-3" style="font-size:13px">
        <div class="col-sm-4">
            <div class="swms-label">Report title</div>
            <div class="fw-500">{{ $report->title }}</div>
        </div>
        <div class="col-sm-2">
            <div class="swms-label">Type</div>
            <div>{{ ucfirst($report->type) }}</div>
        </div>
        <div class="col-sm-2">
            <div class="swms-label">Period</div>
            <div>{{ ucfirst($report->period) }}</div>
        </div>
        <div class="col-sm-2">
            <div class="swms-label">Generated by</div>
            <div>{{ $report->generatedBy->name }}</div>
        </div>
        <div class="col-sm-2">
            <div class="swms-label">Generated on</div>
            <div>{{ $report->created_at->format('d M Y, g:i A') }}</div>
        </div>
        @if($report->from_date)
        <div class="col-sm-4">
            <div class="swms-label">Date range</div>
            <div>{{ $report->from_date->format('d M Y') }} — {{ $report->to_date?->format('d M Y') ?? 'Present' }}</div>
        </div>
        @endif
    </div>
</div>

@if($report->data)
<div class="swms-card">
    <div class="card-title mb-3"><i class="ti ti-table"></i> Report data</div>
    <div class="table-responsive">
        <table class="swms-table">
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach($report->data as $key => $value)
                <tr>
                    <td class="fw-500">{{ ucwords(str_replace('_', ' ', $key)) }}</td>
                    <td>
                        @if(is_array($value))
                            <div class="d-flex flex-wrap gap-2">
                                @foreach($value as $k => $v)
                                    <span style="font-size:12px;background:var(--green-light);color:var(--green);padding:2px 8px;border-radius:6px">
                                        {{ $k }}: {{ $v }}
                                    </span>
                                @endforeach
                            </div>
                        @else
                            <span class="mono">{{ $value }}</span>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endif

@endsection
